---
title: "Identity Masking with Class Roll Data"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(knitr)
```

### Data

```{r, data}
class_roll <- read.xlsx("../data/class_roll0303.xlsx", 
                        sheetIndex = 1, 
                        startRow = 2, 
                        endRow = 162, 
                        colIndex = c(3:7, 9), 
                        colClasses = rep("character", 6), 
                        encoding = "UTF-8", 
                        stringsAsFactors = FALSE)
names(class_roll) <- c("dept", "id", "name", "year", "email", "cell_no")
```

### 학번 가리기

학번은 입학연도를 나타내는 첫 네자리와 개인 식별번호로 구성되어 있다. 여기서,  
개인식별번호를 "9999"로 가려보자. `substr() <-` 을 이용하면 학번의 개인정보를 가리는 일은 한 줄의 코드로 가능하다. 

```{r}
substr(class_roll$id, start = 5, stop = 8) <- "9999"
kable(head(class_roll))
```

### Names

`substring() <- `을 이용하면 각 이름의 2번째 글자 이후를 모두 "ㅇㅇ"으로 대체할 수 있다. 

```{r}
substring(class_roll$name, 2) <- "ㅇㅇ"
kable(head(class_roll))
```

### Cell Phone Numbers

모바일 폰 번호의 끝 네 자리를 "xxxx" 로 대체한다. 정상적으로 번호가 나올 경우 열번째 글자부터 열세번째글자에 해당한다.

```{r, cell_no}
substring(class_roll$cell_no, 10, 13) <- "xxxx"
kable(head(class_roll))
```

### e-mail

email 주소는 `@`를 사이에 두고 나뉘어지므로 앞의 방법을 그대로 적용할 수 없다. email 주소에서 서비스업체만 그대로 두고 개인 식별이 가능한 이름 부분은 `user_name`으로 대체

```{r, e_mail}
email_na <- which(is.na(class_roll$email))
class_roll$email[email_na] <- "NA@NA"
email_split <- sapply(class_roll$email, 
                      function(x) unlist(strsplit(x, split = "@")))
# email_split
email_split[1, ] <- "user_name"
class_roll$email <- apply(email_split, 
                          MARGIN = 2, 
                          paste, collapse = "@")
kable(head(class_roll))
```




<!--
```{r, save}
write.table(class_roll, file ="../data/class_roll_masked.txt")
save.image("../R/class_roll_170303_data_masked.RData")
```
-->