---
# title: "Red and Black 170303 : Names Masked"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

### Data

```{r, data}
class_roll <- read.table("../data/class_roll_masked.txt", 
                         header = TRUE, 
                         encoding = "UTF-8",
                         stringsAsFactors = FALSE)
str(class_roll)
```

### Randomization

```{r, randomization}
set.seed(107)
N <- nrow(class_roll) 
class_roll$group <- sample(1:N) %% 2
class_roll$group <- factor(class_roll$group, levels = c(0, 1), labels = c("Red", "Black"))
red_id <- which(class_roll$group == "Red")
black_id <- which(class_roll$group == "Black")
```

### 학번

```{r, id}
ID_16 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2016, "younger_16", "older_16"), 
                levels = c("younger_16", "older_16"))
kable(table("그룹" = class_roll$group, "16학번 기준" = ID_16), align = "c")
ID_15 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2015, "younger_15", "older_15"), 
                levels = c("younger_15", "older_15"))
kable(table("그룹" = class_roll$group, "15학번 기준" = ID_15), align = "c")
ID_14 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2014, "younger_14", "older_14"), 
                levels = c("younger_14", "older_14"))
kable(table("그룹" = class_roll$group, "14학번 기준" = ID_14), align = "c")
ID_13 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2013, "younger_13", "older_13"), 
                levels = c("younger_13", "older_13"))
kable(table( "그룹" = class_roll$group, "13학번 기준" = ID_13), align = "c")
```

<!--
### 학번 홀짝

```{r, odd or even}
odd_even <- as.numeric(class_roll$id) %% 2
kable(table("Group"= class_roll$group, "odd_even" = odd_even), align = "c")
```
-->

### e-mail 서비스업체

```{r, e_mail}
email_list <- strsplit(class_roll$email, "@", fixed = TRUE)
mail_com <- sapply(email_list, "[", 2)
kable(table("그룹" = class_roll$group, "e-mail" = mail_com), align = "c")
```

### 성씨 분포

```{r, name}
f_name <- substring(class_roll$name, first = 1, last = 1)
kable(table("Group" = class_roll$group, "Family Name" = f_name), align = "c")
```

### 많이 나오는 성씨

```{r, frequent names}
f_name_f <- factor(ifelse(f_name %in% c("김", "이", "박"), f_name, "기타"), 
                   levels = c("김", "이", "박", "기타"))
kable(table("Group" = class_roll$group, "Family Name" = f_name_f), align = "c")
```

### 학과

```{r, departments}
# kable(class_roll)
kable(table("그룹" = class_roll$group, "학과" = class_roll$dept), align = "c")
```

### 전체 출석부

```{r, colleges}
kable(class_roll)
```

<!--
```{r, save}
save.image("../R/red_and_black_170303_data_masked.RData")
```
-->